name: action_sample_wg_random
description: Set up WireGuard connection
runs:
  using: composite
  steps:
    - run: |
        sudo git clone https://github.com/P3TERX/warp.sh
        cd warp.sh
        sudo bash warp.sh install
        sudo bash warp.sh proxy
        sudo bash warp.sh status
      shell: bash
branding:
  icon: star
  color: green
